repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0  # You can specify the latest version here
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0  # Specify the latest version
    hooks:
      - id: flake8
        args: [--max-line-length=88]  # Example argument, adjust as needed

